/**
 * Listener messages shown in the reserved rail.
 * Real Instagram comments (handles + local avatars).
 * Shuffled on every page load.
 *
 * Format: { handle, name, text, avatar, heart }
 */
window.LAOUSMAIL_COMMENTS = [
  {"handle": "@lynda.artofdreaming", "name": "Lynda | Algérienne à Paris 🇩🇿🇫🇷", "text": "Traduction 👇 قالو قالولي قالو قالولي قال قال قال قالو الناس قالولي عليك هدرولي ضربوني قطعوني ربطو نحاو قطعو ياربي هبلوني", "avatar": "avatars/lynda.artofdreaming.jpg", "heart": true},
  {"handle": "@_.gizemli._.kiz._", "name": "✨️witchy🖤✨️", "text": "A dizan win ikren kan adikhdem la chanson thura, tekhram uk la musique kabyle 😑", "avatar": "avatars/_.gizemli._.kiz._.jpg", "heart": true},
  {"handle": "@jiji_juojuo_06", "name": "𓆙ⵣ𝓳𝓾𝓸𝓳𝓾𝓸☯♪♬", "text": "😂❤️", "avatar": "avatars/jiji_juojuo_06.jpg", "heart": true},
  {"handle": "@kessikahina53gmail.com3", "name": "kessikahina53@gmail.com", "text": "Bravo", "avatar": "avatars/kessikahina53gmail.com3.jpg", "heart": true},
  {"handle": "@dr.sourires", "name": "DrSourires", "text": "'@letacofficial tu connais ?.je vous verrai bien collabrer🙌", "avatar": "avatars/dr.sourires.jpg", "heart": true},
  {"handle": "@yacine_bal127", "name": "ⵍⵉⴱⴰⵔⵜⴰ", "text": "Ah je kiffe amigo @laousmail 🫡✅", "avatar": "avatars/yacine_bal127.jpg", "heart": true},
  {"handle": "@lftlmjhwl1406", "name": "sweet girl", "text": "Bravo wlh t3ejbiyi🔥❤️", "avatar": "avatars/lftlmjhwl1406.jpg", "heart": true},
  {"handle": "@romii_1519", "name": "romii_1519", "text": "😂😂", "avatar": "avatars/romii_1519.jpg", "heart": true},
  {"handle": "@tata37195", "name": "tata", "text": "Et la voix c'est la classe😍🔥❤️", "avatar": "avatars/tata37195.jpg", "heart": true},
  {"handle": "@nanee__x10", "name": "🦢🥀", "text": "Ja3la4 achoutt la langue agi alami isli4 imeden😂😂😂😂", "avatar": "avatars/nanee__x10.jpg", "heart": true},
  {"handle": "@lina_lassouef", "name": "Lina ᯓ★", "text": "Belle chanson, kemmel😍", "avatar": "avatars/lina_lassouef.jpg", "heart": true},
  {"handle": "@emma_rima_487", "name": "🌸 Emma 🌸🩷", "text": "Uthem3in arak akhali win i3edan diskhuzedh calma calma 😂🤏🏻", "avatar": "avatars/emma_rima_487.jpg", "heart": true},
  {"handle": "@sha_ely1", "name": "sha_ely1", "text": "افعلها افعلها افعلها افعلها", "avatar": "avatars/sha_ely1.jpg", "heart": true},
  {"handle": "@axiom_ani", "name": "✠ ᴜʀɴɪɴᴏᴜ ✠", "text": "Ttughac nni xdmegh i toilette", "avatar": "avatars/axiom_ani.jpg", "heart": true},
  {"handle": "@houda_boudghaghen", "name": "😸😸😸😸😸", "text": "Welah dessa7😂", "avatar": "avatars/houda_boudghaghen.jpg", "heart": true},
  {"handle": "@m_.ram_4", "name": "🫦✨", "text": "🩷🙂", "avatar": "avatars/m_.ram_4.jpg", "heart": true},
  {"handle": "@cabaneghania", "name": "cabaneghania", "text": "بالحراكات تفهم واش راهو يقول", "avatar": "avatars/cabaneghania.jpg", "heart": true},
  {"handle": "@tima__dr", "name": "Tî Mâ 🕊️", "text": "Achkitt😂", "avatar": "avatars/tima__dr.jpg", "heart": true},
  {"handle": "@_tinhin_nane", "name": "_tinhin_nane", "text": "Dizan wagi", "avatar": "avatars/_tinhin_nane.jpg", "heart": true},
  {"handle": "@social_7home", "name": "Social🏷️", "text": "حسيت شغل يقول ناس تهدر عليا وانا مش سامع بيهم 😂😂😂", "avatar": "avatars/social_7home.jpg", "heart": true},
  {"handle": "@meelissa.amr", "name": "𝗠𝗲𝗹𝗶𝘀𝘀𝗮 🌻", "text": "Bele3 dila3nayek tdhergem ukk la musique kabyle", "avatar": "avatars/meelissa.amr.jpg", "heart": true},
  {"handle": "@hamzaledjedel", "name": "اميرا يتو", "text": "اغنية قبايلية", "avatar": "avatars/hamzaledjedel.jpg", "heart": true},
  {"handle": "@mayas_amrn", "name": "MÄXŸÄS", "text": "Youghal madame noufikha achut l style ni 😂", "avatar": "avatars/mayas_amrn.jpg", "heart": true},
  {"handle": "@nanouu__mb", "name": "☆", "text": "وين تسكن باش نجي نسبك", "avatar": "avatars/nanouu__mb.jpg", "heart": true},
  {"handle": "@nadir_mllk", "name": "𝒩𝒶𝒹𝒾𝓇♓️❤️‍🔥", "text": "Achut chughl agi", "avatar": "avatars/nadir_mllk.jpg", "heart": true},
  {"handle": "@ibraal_bouch", "name": "BOUCHRA", "text": "وين تسكن باه نجي نسبك. معاها", "avatar": "avatars/ibraal_bouch.jpg", "heart": true},
  {"handle": "@maylena_999", "name": "maylena_999", "text": "ble3 takhnak l3naya rbi", "avatar": "avatars/maylena_999.jpg", "heart": true},
  {"handle": "@lunivers.de.bina", "name": "L’univers de Bina 🌹", "text": "Je kiff trop 😍", "avatar": "avatars/lunivers.de.bina.jpg", "heart": true},
  {"handle": "@nesrineladjouzi", "name": "Ladj Nes", "text": "👏👏👏👏👏👏👏👏👏👏❤️", "avatar": "avatars/nesrineladjouzi.jpg", "heart": true},
  {"handle": "@nour_hane.x_25", "name": "Nour_hane_ Foula", "text": "فهمت", "avatar": "avatars/nour_hane.x_25.jpg", "heart": true},
  {"handle": "@dr.mira_wiss", "name": "mira_wiss", "text": "لي ماشي قبايلي تحشاتلو هههههه ايشكيت ثشبح تيكلت اتامزواروث غا اتسلف", "avatar": "avatars/dr.mira_wiss.jpg", "heart": true},
  {"handle": "@maissamicou", "name": "Maïssa Micou", "text": "انا قبايلية و مافهمتهاش", "avatar": "avatars/maissamicou.jpg", "heart": true},
  {"handle": "@lapr.incesse1000", "name": "la princesse", "text": "🔥🔥🔥🔥❤️", "avatar": "avatars/lapr.incesse1000.jpg", "heart": true},
  {"handle": "@thegod_sniper", "name": "AZ Aflalaye", "text": "What no pussy does to a mf", "avatar": "avatars/thegod_sniper.jpg", "heart": true},
  {"handle": "@caramiil_17_.00", "name": "Caramel ♡🍯 🍮", "text": "❤️❤️achkitt", "avatar": "avatars/caramiil_17_.00.jpg", "heart": true},
  {"handle": "@elyanelyan819", "name": "Elyane Illoula", "text": "في الأول مافهمتش بصح كي ركزت فلادوزيام فوا فهمت👏🙌", "avatar": "avatars/elyanelyan819.jpg", "heart": true},
  {"handle": "@naigela3", "name": "꧁ ⵣ 𝑺𝒂𝒓𝒂 ꧂ ✨", "text": "😂😂😂😂😂", "avatar": "avatars/naigela3.jpg", "heart": true},
  {"handle": "@man_ima9", "name": "ⵎⴰⵏⴰⵍ💗✨", "text": "Waqila hala nek ouyite3jiv ara😂", "avatar": "avatars/man_ima9.jpg", "heart": true},
  {"handle": "@monkey_sahara_soul", "name": "Sahara nomad touareg life style", "text": "Nantam nantass", "avatar": "avatars/monkey_sahara_soul.jpg", "heart": true},
  {"handle": "@sandral6889", "name": "sandra L", "text": "❤️❤️❤️", "avatar": "avatars/sandral6889.jpg", "heart": true},
  {"handle": "@ines.inin", "name": "ines", "text": "Bravo 👏👏👏", "avatar": "avatars/ines.inin.jpg", "heart": true},
  {"handle": "@toufikchabli", "name": "Toufik", "text": "الموسيقى حرام", "avatar": "avatars/toufikchabli.jpg", "heart": true},
  {"handle": "@adouda__mazri", "name": "𝕬𝖉𝖔𝖚𝖉𝖆 𝕸𝖆𝖟𝖗𝖎 ✨️", "text": "Texram AK teqvaylit ataxbizt😒😒", "avatar": "avatars/adouda__mazri.jpg", "heart": true},
  {"handle": "@kahinabacha", "name": "Perle Noire", "text": "❤️❤️❤️❤️❤️❤️", "avatar": "avatars/kahinabacha.jpg", "heart": true},
  {"handle": "@asma_asma_8lili_lili_", "name": "✨💕Asma", "text": "😂thlha", "avatar": "avatars/asma_asma_8lili_lili_.jpg", "heart": true},
  {"handle": "@amelbaghedaoui", "name": "✨🩷Amel 🩷✨", "text": "😂😂😂😂ahlil rebbi", "avatar": "avatars/amelbaghedaoui.jpg", "heart": true},
  {"handle": "@yudas_inuri", "name": "ⵢⵓⴷⴷⴰⵙ 🦖ⵣ", "text": "❤️❤️🔥", "avatar": "avatars/yudas_inuri.jpg", "heart": true},
  {"handle": "@cylia686", "name": "Cici Cylia", "text": "😂😂😂", "avatar": "avatars/cylia686.jpg", "heart": true},
  {"handle": "@zineb4082zineb", "name": "Zîneb zineb", "text": "Nek fehmegh les kabylle", "avatar": "avatars/zineb4082zineb.jpg", "heart": true},
  {"handle": "@sam._.bzn", "name": "sb", "text": "C'est clair c'est quasi intraduisible", "avatar": "avatars/sam._.bzn.jpg", "heart": true},
  {"handle": "@mimelblanco", "name": "Ryme Fella", "text": "Belles paroles 👏", "avatar": "avatars/mimelblanco.jpg", "heart": true},
  {"handle": "@vi_be__ss", "name": "vi_be__ss", "text": "Machi aka ikhus snaghk dargaz l3ali uthxdmedh ara thigi thehawlik dahewel canada", "avatar": "avatars/vi_be__ss.jpg", "heart": true},
  {"handle": "@rahilo_v1", "name": "🌫️♣️金門刺眼🖤🌑", "text": "Ilove it 🙌", "avatar": "avatars/rahilo_v1.jpg", "heart": true},
  {"handle": "@sou_ma_dz17", "name": "Sou Ma", "text": "فهمت عولت نقسمنيا 😂😂😂😂😂", "avatar": "avatars/sou_ma_dz17.jpg", "heart": true},
  {"handle": "@islam_ben.06_", "name": "islam_ben.06_", "text": "❤️😍", "avatar": "avatars/islam_ben.06_.jpg", "heart": true},
  {"handle": "@romaissa138", "name": "romaissa13", "text": "فهمت كلش", "avatar": "avatars/romaissa138.jpg", "heart": true},
  {"handle": "@kamylea3", "name": "سَلْسَبِيلْ 👑 💗", "text": "حملغ لاشونصوياكي ♓🔰💛 😍", "avatar": "avatars/kamylea3.jpg", "heart": true},
  {"handle": "@lea1.232810", "name": "Léa Idoughì✪", "text": "Nekk fehmeght merra", "avatar": "avatars/lea1.232810.jpg", "heart": true},
  {"handle": "@marouane_oufella_2008", "name": "Marouane Oufella", "text": "Toop ayahevive👏👏🔥🔥", "avatar": "avatars/marouane_oufella_2008.jpg", "heart": true},
  {"handle": "@safia_ysd", "name": "Safia Ysd", "text": "🔥🔥🔥🔥🔥", "avatar": "avatars/safia_ysd.jpg", "heart": true},
  {"handle": "@imane_bouassou_128", "name": "Îmãňë Bøu", "text": "مدن اسولن ربي اهدي مخلق😂", "avatar": "avatars/imane_bouassou_128.jpg", "heart": true},
  {"handle": "@h_283_kdr", "name": "𝑯𝑨𝑫𝑱𝑬𝑹♕", "text": "والله غير اناناناني صح 🥲✨", "avatar": "avatars/h_283_kdr.jpg", "heart": true},
  {"handle": "@zinadant", "name": "Zina", "text": "Ils m'ont dit qu'ils ont parlé sur moi...", "avatar": "avatars/zinadant.jpg", "heart": true},
  {"handle": "@f_eyyy___", "name": "🥥", "text": "❤️❤️", "avatar": "avatars/f_eyyy___.jpg", "heart": true},
  {"handle": "@owl.9574014", "name": "owl.9574014", "text": "Ahhh inyd wlh 😂😂", "avatar": "avatars/owl.9574014.jpg", "heart": true},
  {"handle": "@ines_nini17", "name": "ines", "text": "Formidable bon continuation vivi taqbaylit ❤️", "avatar": "avatars/ines_nini17.jpg", "heart": true},
  {"handle": "@nora402314", "name": "Kabyl'Orient by Nora 💫", "text": "🔥🔥🔥👏", "avatar": "avatars/nora402314.jpg", "heart": true},
  {"handle": "@tata37195", "name": "tata", "text": "Jadoooor❤️👏🔥😍", "avatar": "avatars/tata37195.jpg", "heart": true},
  {"handle": "@lamin_311246", "name": "ŁŤNĞ", "text": "Ayaxniw", "avatar": "avatars/lamin_311246.jpg", "heart": true},
  {"handle": "@laprincesse2104", "name": "𝑽𝒆𝒍𝒐𝒖𝒓𝒂", "text": "Temlah ❤️❤️❤️🔥", "avatar": "avatars/laprincesse2104.jpg", "heart": true},
  {"handle": "@anyst.asi", "name": "anyst.asi", "text": "Fehmagh akken ilaq ♓️😏", "avatar": "avatars/anyst.asi.jpg", "heart": true},
  {"handle": "@fan", "name": "fan", "text": "… 23 more comments not included in this free sample — unlock all 101 at https://zocialcomment.com/export/e55df077-c7c8-452b-bb74-72c33a59070e", "avatar": "", "heart": true},
]

