/**
 * Listener messages shown in the reserved rail.
 * Paste real comments anytime. No source labels are shown on the page.
 *
 * Format:
 *   { handle: '@someone', text: 'comment', heart: true }
 *
 * A floating “Leave a message for Smail” tab is injected automatically
 * and streams with the other bubbles. On each page load the rail shuffles
 * this pool (merged with any live remote / local comments).
 */
window.LAOUSMAIL_COMMENTS = [
  { handle: "@fan", text: "L'essentiel c'est que ça m'a plu beaucoup", heart: true },
  { handle: "@fan", text: "Je te souhaite beaucoup de succès", heart: true },
  { handle: "@lya", text: "Finalement tu chantes depuis longtemps", heart: true },
  { handle: "@nova", text: "Je viens de te découvrir", heart: true },
  { handle: "@kira", text: "Et j'adore", heart: true },
  { handle: "@orbit", text: "This orbit hits different at night", heart: true },
  { handle: "@mika", text: "La voix est trop douce, on reste collé", heart: true },
  { handle: "@jade", text: "Playing LAOUSMAIL on loop since the show", heart: true },
  { handle: "@enzo", text: "C'est hypnotique, vraiment", heart: true },
  { handle: "@sol", text: "The drop feels like floating", heart: true },
  { handle: "@nina", text: "Qui d'autre est dans l'orbite ce soir ?", heart: true },
  { handle: "@rex", text: "Underrated artist, tell your friends", heart: true },
  { handle: "@cleo", text: "J'ai mis le titre en favori direct", heart: true },
  { handle: "@ash", text: "Show was magic. Still buzzing.", heart: true },
  { handle: "@leo", text: "Smail, continue exactement comme ça", heart: true },
  { handle: "@iris", text: "Soft vocals + that pulse = perfect", heart: true },
  { handle: "@tom", text: "Je découvre et je regrette pas", heart: true },
  { handle: "@vae", text: "Orbit mode on. Headphones only.", heart: true },
  { handle: "@lou", text: "Ça me donne des frissons", heart: true },
  { handle: "@kit", text: "New favorite late-night listen", heart: true },
  { handle: "@aya", text: "La mélodie reste dans la tête", heart: true },
  { handle: "@zen", text: "Clean production, warm emotion", heart: true },
  { handle: "@rio", text: "Qui vient au prochain show ?", heart: true },
  { handle: "@mae", text: "I felt every lyric", heart: true },
  { handle: "@bob", text: "Trop fort. Encore une fois.", heart: true },
  { handle: "@sky", text: "This track belongs in the cosmos", heart: true },
  { handle: "@eli", text: "Merci pour l'ambiance", heart: true },
  { handle: "@fox", text: "Replay button is broken… in a good way", heart: true },
  { handle: "@sam", text: "La scène était magnifique", heart: true },
  { handle: "@pip", text: "Sending love from the orbit crew", heart: true },
  { handle: "@noe", text: "Chanson du moment, sans débat", heart: true },
  { handle: "@joy", text: "So cinematic. I closed my eyes.", heart: true },
  { handle: "@ben", text: "Le live était encore mieux", heart: true },
  { handle: "@rui", text: "Bass + breathy vocals = yes", heart: true },
  { handle: "@ada", text: "Je partage ça à tout le monde", heart: true },
  { handle: "@kai", text: "LAOUSMAIL in my top 2026 already", heart: true },
  { handle: "@ume", text: "Douceur et puissance en même temps", heart: true },
  { handle: "@ty", text: "That bridge is unreal", heart: true },
  { handle: "@cam", text: "On danse tout seul chez soi", heart: true },
  { handle: "@ned", text: "Found you through a friend. Hooked.", heart: true },
  { handle: "@oya", text: "L'énergie du show reste en moi", heart: true },
  { handle: "@gil", text: "Atmospheric and intimate at once", heart: true },
  { handle: "@pia", text: "Smail a une vraie signature", heart: true },
  { handle: "@jon", text: "Putting this on every playlist", heart: true },
  { handle: "@eve", text: "Encore un tour dans l'orbite", heart: true },
  { handle: "@max", text: "Vocals sit so nicely in the mix", heart: true },
  { handle: "@tia", text: "J'attends la prochaine date", heart: true },
  { handle: "@hal", text: "Night drive soundtrack secured", heart: true },
  { handle: "@omi", text: "Beau, triste, lumineux. Tout.", heart: true },
  { handle: "@dex", text: "This is the sound of the room after midnight", heart: true },
  { handle: "@liv", text: "Tu touches juste", heart: true },
  { handle: "@quo", text: "Melody stuck on day three", heart: true },
  { handle: "@vie", text: "Bravo pour le live, sincèrement", heart: true },
  { handle: "@neo", text: "Subtle, then it hits. Love it.", heart: true },
  { handle: "@rin", text: "Orbit vibes all week", heart: true },
  { handle: "@gus", text: "La voix porte vraiment loin", heart: true },
  { handle: "@amy", text: "Took my friends. They get it now.", heart: true },
  { handle: "@ibo", text: "Trop beau pour un premier écoute", heart: true },
  { handle: "@cal", text: "Keep the orbit spinning", heart: true },
  { handle: "@nea", text: "Je reviens juste pour ce titre", heart: true },
  { handle: "@pod", text: "Headphones recommended. Trust me.", heart: true },
  { handle: "@sio", text: "Émotion pure du début à la fin", heart: true },
  { handle: "@wes", text: "Stage lights + this song = goosebumps", heart: true },
  { handle: "@uli", text: "Smail, on te suit", heart: true },
  { handle: "@bay", text: "Soft fire. That's the vibe.", heart: true },
  { handle: "@cio", text: "La prod est soignée", heart: true },
  { handle: "@dre", text: "Sharing with everyone who likes night music", heart: true },
  { handle: "@fen", text: "Encore une écoute… et une autre", heart: true },
  { handle: "@hex", text: "Orbit playlist essential", heart: true },
  { handle: "@izo", text: "Merci pour ce moment", heart: true },
  { handle: "@jem", text: "Heard it once, stayed forever", heart: true },
  { handle: "@kyo", text: "Ça respire. Ça pulse.", heart: true },
  { handle: "@lux", text: "Beautiful tension in every bar", heart: true },
  { handle: "@mio", text: "Le refrain m'a eu", heart: true },
  { handle: "@nix", text: "This belongs under the stars", heart: true },
  { handle: "@oro", text: "Fan depuis le premier passage", heart: true },
  { handle: "@paz", text: "Quiet loudness. I love that.", heart: true },
  { handle: "@qin", text: "On veut la tournée", heart: true },
  { handle: "@roy", text: "Saved. Shared. Obsessed.", heart: true },
  { handle: "@sia", text: "La texture de la voix… wow", heart: true },
  { handle: "@ted", text: "Show energy transferred perfectly", heart: true },
  { handle: "@una", text: "Je mets ça en fond et je rêve", heart: true },
  { handle: "@val", text: "Orbit never sounded this warm", heart: true },
  { handle: "@wyn", text: "Très fort. Continue.", heart: true },
  { handle: "@xem", text: "The silence between notes hits too", heart: true },
  { handle: "@yul", text: "Coup de cœur immédiat", heart: true },
  { handle: "@zoe", text: "Taking this into the weekend", heart: true },
  { handle: "@ari", text: "Smail, ta musique m'accompagne", heart: true },
  { handle: "@blu", text: "That live version lives rent-free", heart: true },
  { handle: "@cy", text: "Encore plus beau en vrai", heart: true },
  { handle: "@dot", text: "Minimal, emotional, sticky", heart: true },
  { handle: "@eco", text: "L'orbite tourne et moi avec", heart: true },
  { handle: "@flo", text: "Put it on when the city sleeps", heart: true },
  { handle: "@gio", text: "Respect total pour le parcours", heart: true },
  { handle: "@hue", text: "I hear heart in every line", heart: true },
  { handle: "@ivy", text: "Titre du soir, sans hésiter", heart: true },
  { handle: "@jax", text: "Coming back for the next orbit", heart: true },
  { handle: "@kel", text: "Musique qui reste après le silence", heart: true },
  { handle: "@lyn", text: "This is my calm and my lift", heart: true },
  { handle: "@moe", text: "LAOUSMAIL forever in the rotation", heart: true },

  // Paste real TikTok / Instagram comments below
  // { handle: '@real_handle', text: 'exact comment text', heart: true },
]
